### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by ClaudiuFilip110** [nyanp/chat2plot#7]
I'm trying to use the library, but I can't, and I can't figure out why. 

When loading the library `from chat2plot import chat2plot` I'm getting the TypeError. I've tried Python 3.9 and 3.11.

My machine is a M1 Pro, if that helps. To recreate, you just do `pip install chat2plot`.

**Comment by nyanp** [comment]
@ClaudiuFilip110 
This library supports Python 3.10 and above. The error appears to be due to Python 3.9 not supporting union types.
If you get the same error with Pyyhon 3.11, please provide a complete stack trace.

**Comment by mcolas-starzdata** [comment]
I have the same issue, and forced to use Python 3.10 as recommended.

Here is the trasceback : 

 File "/Users/mathieucolas/Library/Caches/pypoetry/virtualenvs/szd-BHbK659G-py3.10/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/mathieucolas/StarzdataEnterpriseHub/webapp/app.py", line 10, in <module>
    from webapp.datasets import datasets_area, dataset_profile_area, selected_dataset_has_data, chat2plot_area
  File "/Users/mathieucolas/StarzdataEnterpriseHub/webapp/datasets.py", line 24, in <module>
    from chat2plot import chat2plot
  File "/Users/mathieucolas/Library/Caches/pypoetry/virtualenvs/szd-BHbK659G-py3.10/lib/python3.10/site-packages/chat2plot/__init__.py", line 1, in <module>
    from chat2plot.chat2plot import (  # noQA
  File "/Users/mathieucolas/Library/Caches/pypoetry/virtualenvs/szd-BHbK659G-py3.10/lib/python3.10/site-packages/chat2plot/chat2plot.py", line 59, in <module>
    _PROMPT = _build_prompt()
  File "/Users/mathieucolas/Library/Caches/pypoetry/virtualenvs/szd-BHbK659G-py3.10/lib/python3.10/site-packages/chat2plot/chat2plot.py", line 28, in _build_prompt
    schema_json = json.dumps(get_schema_of_chart_config(inlining_refs=True), indent=2)
  File "/Users/mathieucolas/Library/Caches/pypoetry/virtualenvs/szd-BHbK659G-py3.10/lib/python3.10/site-packages/chat2plot/schema.py", line 239, in get_schema_of_chart_config
    schema = inlining_refs_in_schema(schema)
  File "/Users/mathieucolas/Library/Caches/pypoetry/virtualenvs/szd-BHbK659G-py3.10/lib/python3.10/site-packages/chat2plot/schema.py", line 225, in inlining_refs_in_schema
    defs = list(schema["definitions"].keys())
    KeyError: 'definitions'
2024-02-07 14:41:56.440 Uncaught app exception
Traceback (most recent call last):
  File "/Users/mathieucolas/Library/Caches/pypoetry/virtualenvs/szd-BHbK659G-py3.10/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
